### ISSUE TITLE
[공지] 2021년 동계 학부연구생 사전 신청 예시

### ISSUE THREAD

**Issue by unizard** [sejong-rcv/URP#1]
## 신청 예시?
- 최세종 / sejong@sejong.ac.kr
- 지능기전공학부 / 3학년
- 미필(석사전문연희망, 박사전문연희망) 혹은 군필 혹은 여성
- 학부연구생 신청 사유
  - 대학원 진학을 고려 중이며, 컴퓨터비전이라는 분야가 저와 잘 맞는지 궁금하여 신청합니다.

## 신청은?
- 아래의.댓글로

**Comment by skyil7** [comment]
- 백지오/giopaik@naver.com
- 컴퓨터공학과 / 2학년
- 미필 (2021년 3월 입대 예정)
- 신청 사유: 전역 후 학부 연구생 및 대학원 진학을 할 계획이며, 컴퓨터비전 분야에 관심이 있어 URP를 통해 대학원과 컴퓨터 비전 분야 연구를 체험해보고 추후 진학을 준비할 수 있는 기회로 삼고자 신청합니다!

**Comment by tobe-honest** [comment]
● 김진명 / kimjinm0@naver.com
● 지능기전공학부 / 2학년
● 군필(석사전문연희망)
● 학부연구생 신청 사유
      ○ 미래에 내가 무슨 일을 해야 할지 어떠한 일이 나에게 즐거운 일이 될지에 대해서 생각하고 선택하는 것은 많은 사람들의 평생의 숙제 아닌 숙제라 생각합니다. 저도 이러한 숙제를 안고 살아가며 그러한 때가 있을 때마다 고민을 하며 숙제를 하나씩 해결해 왔습니다. 하지만 수많은 생각과 선택을 하는 시기 중에서 제일 중요한 시기가 지금 찾아왔다고 생각합니다. 한참을 고민하다 고민만 하지 말고 직접 해보자 생각을 해서 앱, 웹 프런트엔드 공부도 해보고 백엔드에 관해서도 찾아보고 머신러닝도 찾아보며 공부를 하고 있습니다. 그중에서 재미있고 신기하고 바로 마음에 와닿는 느낌이 든 것은 머신러닝이었습니다. 아직 머신러닝 공부의 초반부에 불과하지만 제 경험상 처음부터 재미가 있는 것은 대체적으로 오래 지속되어도 즐겁다 판단했습니다. 그래서 머신러닝을 다루는 직업을 갖기 위해선 어떻게 해야 할까 찾아보았는데 거의 대부분 대학원을 진학을 해야 한다는 사실을 알았습니다. 물론 대학원에 진학하기 위해선 연구 실적이 중요하고 연구 실적을 내려면 연구실에 속해서 연구를 하는 방법뿐이라 생각이 들었습니다. 여러 연구실 중 Robotics and Computer Vision Lab.에 지원을 하게 된 이유 중 첫 번째는 제가 생각하는 머신러닝이 컴퓨터 비전이라 생각했기 때문입니다. 저는 머신러닝을 생각하면 제일 먼저 떠오르는 것이 사진을 라벨링하고 학습시키는 것인데 이것은 컴퓨터 비전의 아주 기초라 생각합니다. 두 번째는 서론에서 언급 한 것처럼 즐거운 일을 해야 한다고 생각하는데 즐거운 일이란 일 자체에 대한 흥미 + 조직의 구조(일하는 방식, 조직이 운영되는 구조)가 모두 충족되어야 된다고 생각합니다. 즐거운 일이 되는 첫 번째 조건인 일 자체에 대한 흥미는 충족되었고 두 번째 조건인 조직의 구조는 Robotics and Computer Vision Lab. 가 충족 시켜줄 것이라 생각했습니다.  최고 수준의 자율성은 최고 수준의 정보 공유에서 나오고 최고 수준의 정보 공유는 최고 수준의 신뢰를 바탕으로 이루어진다는 토스의 문화가 Robotics and Computer Vision Lab.에도 있을 것이라 생각합니다. 그렇기에 본 연구실에 지원합니다.
