### ISSUE TITLE
[질문] 2021년 1월, 2월 동안만 활동하게 되는 건가요?

### ISSUE THREAD

**Issue by skyil7** [sejong-rcv/URP#6]
안녕하세요. 교수님.

활동기간에 2021년 1월 ~ 2월이라 되어있는데, 단 2개월 동안만 활동하게 되는 것인가요? (인턴같은 느낌?)

2021년 2월 이후로 활동하기 어려워도 지원해도 되는지 궁굼합니다!

감사합니다 :)

**Comment by unizard** [comment]
@skyil7 이번 동계 활동은 Corvid19 여파로 비대면으로 활동하거나 랜선으로 활동하게 될 확률이 높습니다. 주 활동은 연구실 내에 준비된 교육을 이수하는 것이기에 방학 중에만 활동하셔도 좋습니다. 그럼에도 불구하고 지속적으로 연구실 활동을 할 학생들을 우대하여 선발할 예정이기는 합니다. 참고하시기 바랍니다~

**Comment by skyil7** [comment]
그렇군요! 감사합니다 교수님~
